### PR TITLE
restrict future dates

### PR DESCRIPTION
**Pull request by melanie-adler**

### CODE REVIEW

**Comment by melanie-adler** [comment]
> What has happened here? Where is the rest of the code? I can only see one line of new code. Can you explain to me what happened?

@Roland-Hufnagel We created the US not knowing that the fix would be as simply as adding a max value.

**Review by Roland-Hufnagel — CHANGES_REQUESTED** [review]
Okay - Seems like you had most of the implementation before and only added that line. But it is not working when you edit a transaction. Please try to solve this problem first and post the PR again.

**Comment by melanie-adler** [comment]
@Roland-Hufnagel Unfortunately I cannot recreate your issue with the max date in edit mode. It works fine in the list view as well as in the details view. Could you be more precise as to what is not working correctly here?

**Review by Roland-Hufnagel — COMMENTED** [review]
It seem I made a mistake. I'm sorry for that. It all seems to work fine and let me say: This is really the smallest Codereview I ever did. And it works so fine. Congratulations 💪💪💪💪💪 🚀🚀🚀🚀🚀🚀

**Review by Roland-Hufnagel — APPROVED** [review]

**Pull request merged**
